# Generated by Django 2.2.6 on 2019-10-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='usability',
        ),
    ]
