# Generated by Django 2.2.6 on 2019-10-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_review_usability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='design',
        ),
    ]
